services:
  - type: web
    name: arborgoldfileexport
    env: python
    buildCommand: |
      apt-get update && apt-get install -y \
        wget \
        curl \
        unzip \
        gnupg2 \
        ca-certificates \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libxss1 \
        libnss3 \
        libgdk-pixbuf2.0-0 \
        xdg-utils \
        google-chrome-stable
    startCommand: |
      python main.py
    plan: free
    envVars:
      - key: GOOGLE_CHROME_BIN
        value: "/usr/bin/google-chrome-stable"
      - key: DISPLAY
        value: ":0"
